server:
  host: 0.0.0.0
  port: 8888

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: etroot
  password: asSX855ib5mMcjf4
  dbname: et-order-program
  charset: utf8
  location: Local

secket:
  tokenKey: b9p$43+f$hv0kr6frfr-*^3csv#^k!_##bgn*amz%$it61c!2s

log:
  level: debug
  file: /var/log/ET-order-mini-program.log
